# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
      # Krok 1: Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4
      # Krok 2: Zainstaluj Python i zależności
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Generate Data
        run: |
          python generator_danych.py

      - name: Clean Data
        run: |
           python clean_data.py | tee output.log
           grep "Model trained with accuracy" output.log > accuracy.txt
      # Krok 4: Wyświetl wynik (accuracy)
      - name: Display result
        run: cat accuracy.txt
